#!/bin/zsh

source ~/scripts/utils.sh

if [ -f ".env" ]; then
   source .env
else
   printError "ERROR : Environment file '.env' not found."
   printError "Exiting..."
   exit
fi

banner $MW2_APP_NAME

# $DATABASE_PATH is defined in .env
if [ -n "$DATABASE_PATH" ]; then
   if [ ! -f "$DATABASE_PATH" ]; then
      printMessage "Creating database..."
      sqlx database setup
   else
      printMessage "Found database : '$DATABASE_PATH'"
   fi
else
   printError "ERROR : Environment variable 'DATABASE_PATH' is not defined."
   printError "Exiting..."
   exit
fi

printMessage "Watching..."
sleep 1

cargo leptos watch
